version: "3"
services:
  prereview:
    image: prereview.azurecr.io/prereview:latest
    depends_on:
      - prereview-db
    networks:
      - prereview-private
      - prereview-public
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PREREVIEW_LOG_LEVEL: ${PREREVIEW_LOG_LEVEL:-debug}
      PREREVIEW_HOST: ${PREREVIEW_HOST:-0.0.0.0}
      PREREVIEW_PORT: ${PREREVIEW_PORT:-3000}
      PREREVIEW_DB_TYPE: postgresql
      PREREVIEW_DB_HOST: prereview-db
      PREREVIEW_DB_PORT: 5432
      PREREVIEW_DB_USER: ${PREREVIEW_DB_USER:-prereview}
      PREREVIEW_DB_PASS: ${PREREVIEW_DB_PASS:-prereview}
      PREREVIEW_DB_NAME: ${PREREVIEW_DB_NAME:-prereview}

  prereview-db:
    image: postgres:12-alpine
    volumes:
      - prereview-db_data:/var/lib/postgresql/data
    networks:
      - prereview-private
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PREREVIEW_DB_USER:-prereview}
      POSTGRES_PASSWORD: ${PREREVIEW_DB_PASSWORD:-prereview}
      POSTGRES_DB: ${PREREVIEW_DB_DATABASE:-prereview}

volumes:
  prereview-db_data: {}

networks:
  prereview-private:
    internal: true
  prereview-public:
