version: "3.4"
services:
  prereview:
    build:
      target: integration
    environment:
      FAKETIME: '@2022-08-12 00:00:00'
      PREREVIEW_ADMIN_USERS: '0000-0002-6266-406X'
      PREREVIEW_ORCID_CALLBACK_URL: 'http://prereview:3000/api/v2/orcid/callback'
      TEST_ADMIN_USER_ORCID: '0000-0002-6266-406X'
      TEST_ADMIN_USER_API_APP: 'playwright'
      TEST_ADMIN_USER_API_KEY: 'not-a-secret'

  playwright:
    build:
      context: integration
    depends_on:
      - prereview
    networks:
      - prereview-private
      - prereview-public
    volumes:
      - './integration/playwright.config.ts:/app/playwright.config.ts'
      - './integration/src:/app/src'
      - './integration/results:/app/test-results'
      - './integration/state:/app/state'
    environment:
      BASE_URL: 'http://prereview:3000'
      RETRIES:
      TEST_ADMIN_USER_API_APP: 'playwright'
      TEST_ADMIN_USER_API_KEY: 'not-a-secret'
      TEST_USER_ORCID: '0000-0002-7498-6197'
      TEST_USER_ORCID_PASSWORD: 'this-is-a-secure-passw0rd!'
      TEST_COMMUNITY_MEMBER_ORCID: '0000-0002-6344-7905'
      TEST_COMMUNITY_MEMBER_ORCID_PASSWORD: 'this-is-a-secure-passw0rd!'
      TEST_COMMUNITY_MODERATOR_ORCID: '0000-0002-4045-3747'
      TEST_COMMUNITY_MODERATOR_ORCID_PASSWORD: 'this-is-a-secure-passw0rd!'
