version: "3.4"
services:
  prereview:
    build:
      target: integration
    environment:
      PREREVIEW_ADMIN_USERS: '0000-0002-7498-6197'
      TEST_ADMIN_USER_ORCID: '0000-0002-7498-6197'
      TEST_ADMIN_USER_API_APP: 'playwright'
      TEST_ADMIN_USER_API_KEY: 'not-a-secret'

  playwright:
    build:
      context: integration
    depends_on:
      - prereview
    networks:
      - prereview-private
      - prereview-public
    volumes:
      - './integration/playwright.config.ts:/app/playwright.config.ts'
      - './integration/src:/app/src'
      - './integration/results:/app/test-results'
      - './integration/state:/app/state'
    environment:
      BASE_URL: 'http://prereview:3000'
      RETRIES:
      TEST_ADMIN_USER_API_APP: 'playwright'
      TEST_ADMIN_USER_API_KEY: 'not-a-secret'
