version: "3"
services:
  prereview:
    image: prereview.azurecr.io/prereview:develop
    depends_on:
      - prereview-db
    networks:
      - prereview-private
      - prereview-public
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
      PREREVIEW_LOG_LEVEL: debug
      PREREVIEW_HOST: 0.0.0.0
      PREREVIEW_PORT: 3000
      PREREVIEW_DB_TYPE: postgresql
      PREREVIEW_DB_HOST: prereview-db
      PREREVIEW_DB_PORT: 5432
      PREREVIEW_DB_USER: prereview
      PREREVIEW_DB_NAME: prereview

  prereview-db:
    image: postgres:12-alpine
    networks:
      - prereview-private
    environment:
      POSTGRES_USER: prereview
      POSTGRES_PASSWORD: ${PREREVIEW_DB_PASS}
      POSTGRES_DB: prereview

networks:
  prereview-private:
    internal: true
  prereview-public:
