name: Build and deploy to staging

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY_USERNAME: prereview

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: 'Build image'
        run: make build
        env:
          TARGET: 'prod'

      - name: 'Smoke test'
        run: .github/smoke-test.sh

      - name: 'Log in to registry'
        uses: azure/docker-login@v1
        with:
          login-server: prereview.azurecr.io
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Push image'
        run: docker push prereview.azurecr.io/prereview:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy app'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'prereview2'
          slot-name: 'staging'
          images: prereview.azurecr.io/prereview:${{ env.IMAGE_TAG }}
          configuration-file: './deploy/docker-compose.yml'

  tag:
    runs-on: ubuntu-20.04
    needs: deploy
    continue-on-error: true

    steps:
      - name: 'Tag as latest'
        uses: tinact/docker.image-retag@1.0.3
        with:
          image_name: 'prereview'
          image_old_tag: ${{ env.IMAGE_TAG }}
          image_new_tag: 'latest'
          registry: 'prereview.azurecr.io'
          registry_username: ${{ env.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
