# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - prereview2-dev

on:
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to private registry'
      uses: azure/docker-login@v1
      with:
        login-server: prereview.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build image'
      run: docker-compose build prereview

    - name: 'Smoke test'
      run: .github/smoke-test.sh

    - name: 'Tag image'
      run: docker tag prereview.azurecr.io/prereview:${IMAGE_TAG} prereview.azurecr.io/prereview:latest

    - name: 'Push image'
      run: |
        docker push prereview.azurecr.io/prereview:${IMAGE_TAG}
        docker push prereview.azurecr.io/prereview:latest

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'prereview2'
        slot-name: 'staging'
        configuration-file: './deploy/docker-compose.yml'
